from __future__ import annotations

from typing import Protocol

from app.domain import JobEntity


class JobRepository(Protocol):
    def get_job(self, job_id: str) -> JobEntity | None: ...

    def get_project_job(self, project_id: str, job_id: str) -> JobEntity | None: ...

    def list_project_jobs(self, project_id: str) -> list[JobEntity]: ...

    def get_active_project_job(self, project_id: str) -> JobEntity | None: ...

    def add_job(self, job: JobEntity) -> None: ...

    def update_job(self, job: JobEntity) -> None: ...

    def save(self) -> None: ...
